### ISSUE TITLE
Renaming downloaded fonts

### ISSUE THREAD

**Issue by FTWinston** [AaronJan/postcss-font-grabber#10]
I've used postcss-font-grabber to download a google font at build time and it does that great.

However, an error occurs when I try to use more than one google font.

Because all the google font _files_ are served from a path ending in /font, it downloads all of these to a file called "font" in fontDir.

When more than one file would download to this same filename, they seem to overwrite each other. In any event, only one font file is created, and accessing it causes errors in the browser.

If it were possible to specify a pattern to use when saving downloaded files, that would work around this.
Perhaps that could include placeholders such as the following:
[name] - Returns the file name.
[ext] - Returns the file extension.
[hash] - Returns a hash of  the file content.
[path] - Returns the path of the url the file was downloaded from, adapted to be filename-friendly.
[query] - Returns the query string of the url the file was loaded from, adapted to be filename-friendly.

Does this seem like a feature you'd want to include?

**Comment by AaronJan** [comment]
@FTWinston Thank you! I'm glad you like it!

This is indeed a problem that need to be handled, I think your solution is good, would you like to make a pull request? Or I'll add this feature in the next week.

**Comment by FTWinston** [comment]
I'm happy to give it a go, though I'll warn you I'm very new to postcss.

Thinking about this some more, adding a complicated extra configuration option for filename patterns might be overkill.

If files in fontDir were considered temporary files, then temporary filenames might suffice. (Either random, or hash-based.)

Would you prefer this kind of solution, or a more comfortable approach like I described initially?

**Comment by FTWinston** [comment]
I've raised a couple of pull requests that would resolve this in different ways. Depends if you'd rather keep the configuration to a minimum, or ensure that potentially-unforseen edge cases can be worked around.

Happy to modify either as needed.

**Comment by AaronJan** [comment]
> I've raised a couple of pull requests that would resolve this in different ways. Depends if you'd rather keep the configuration to a minimum, or ensure that potentially-unforseen edge cases can be worked around.
> 
> Happy to modify either as needed.

Impressive, great works! 👏 

I do agree with you, changing the `getFontFilename()` function is better.

PR merged, cheers!

**Comment by AaronJan** [comment]
`v2.2.0` published. 😄

**Comment by FTWinston** [comment]
Awesome, thanks!

**Comment by FTWinston** [comment]
I've updated to v2.2.0, but it doesn't seem to contain the code from #11.

My installed version of postcss-font-grabber/dist/font-grabber/functions.js still has the following:

```
function getFontFilename(fontUriObject) {
    if (!fontUriObject.pathname) {
        return helpers_1.md5(url_1.default.format(fontUriObject));
    }
    return path_1.default.basename(fontUriObject.pathname);
}
```

Which doesn't match what's in the source when I [download v2.2.0 from github](https://github.com/AaronJan/postcss-font-grabber/archive/v2.2.0.zip).

Might the npm release be targetting the wrong commit?

**Comment by AaronJan** [comment]
> I've updated to v2.2.0, but it doesn't seem to contain the code from #11.
> 
> My installed version of postcss-font-grabber/dist/font-grabber/functions.js still has the following:
> 
> ```
> function getFontFilename(fontUriObject) {
>     if (!fontUriObject.pathname) {
>         return helpers_1.md5(url_1.default.format(fontUriObject));
>     }
>     return path_1.default.basename(fontUriObject.pathname);
> }
> ```
> 
> Which doesn't match what's in the source when I [download v2.2.0 from github](https://github.com/AaronJan/postcss-font-grabber/archive/v2.2.0.zip).
> 
> Might the npm release be targetting the wrong commit?

Oops, forgot to run `build` before publishing... `v2.2.1` published, added a `prepare` script to avoid this from happening again.

**Comment by FTWinston** [comment]
Great, thanks for that
