### ISSUE TITLE
Should `mkdir -p` if it doesn't already exist

### ISSUE THREAD

**Issue by niftylettuce** [AaronJan/postcss-font-grabber#3]
could use <https://github.com/substack/node-mkdirp>

**Comment by AaronJan** [comment]
Hi, thanks for your feedback! 👍 
I think `mkdir` is not necessary, because automation tool (like Gulp) usually take care of this, so I just want to keep this simple.

**Comment by niftylettuce** [comment]
I think so too but it would probably be easiest for end user if this was
built in, otherwise no error seems to be thrown?

On Jan 2, 2018 10:05 AM, "AaronJan" <notifications@github.com> wrote:

Hi, thanks for your feedback! 👍
I think mkdir is not necessary, because automation tool (like Gulp) usually
take care of this, so I just want to keep this simple.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AaronJan/postcss-font-grabber/issues/3#issuecomment-354785791>,
or mute the thread

**Comment by AaronJan** [comment]
Yes, it would be nice to have that (but I don't want to use another lib).
I don't have the time to make this change right now, maybe next week.
You can make a PR if you really need this right now, or I'll do this later and review all dependencies. 😃

**Comment by AaronJan** [comment]
@niftylettuce 

I finally got the time to rewrite this, although it's still in alpha stage, but I hope it could win your star. [CLICK HERE FOR `2.0`!](https://github.com/AaronJan/postcss-font-grabber#options)

I will keep working on it, if you have more suggestions, let me know. 😃

**Comment by AaronJan** [comment]
`v2.0.1` released, I think I can close this now.
