### ISSUE TITLE
Hangs if process exits

### ISSUE THREAD

**Issue by niftylettuce** [AaronJan/postcss-font-grabber#4]
`FontGrabber.downloader.download` causes the process to hang and continue to keep downloading files I think?

**Comment by AaronJan** [comment]
Hi 😄 , could you give an example?
What version of PostCSS do you use? (I've been doing backend stuff since last update)

**Comment by niftylettuce** [comment]
I think this may have been due to another package using globby sync.  we
can and close this for now.

**Comment by AaronJan** [comment]
OK.
