### ISSUE TITLE
request for dumping metadata to json file

### ISSUE THREAD

**Issue by WDD-Marv** [AaronJan/postcss-font-grabber#5]
it would be handy for logging/tinkering purposes if the grabbed font remapping was dumped to a json file, preferrably of the form:
```json
{
    "source.css": {
        "https://example.com/font.woff": "./path-to-dir.woff"
    }
}
```

for tinkering purposes, I'd like to use such metadata to force the font to be preloaded if the corresponding source css file is loaded in the document.

**Comment by AaronJan** [comment]
I hear you. 😃 
I'm planning to rewrite this project.

**Comment by AaronJan** [comment]
@WDD-Marv 

You can do that now with [`2.0`](https://github.com/AaronJan/postcss-font-grabber#dig-deeper).

🥂

**Comment by AaronJan** [comment]
`v2.0.1` released, I think I can close this now.

**Comment by WDD-Marv** [comment]
so I got this working, but it turns out preloading fonts is a pointless exercise as the font is downloaded by the stylesheet processing, regardless of whether it has been preloaded or not. :(

cc @jeffposnick

**Comment by AaronJan** [comment]
@WDD-Marv 
For me, preloading fonts could prevent unwanted tracking (by font providers).

This project really isn't that helpful for now, I agree with you.
Maybe we can discover more use cases in the future. 😃
