### ISSUE TITLE
Migrate to PostCSS 8.0

### ISSUE THREAD

**Issue by CREEATION** [AaronJan/postcss-font-grabber#9]
Short and sweet. I'm sure it's on your radar already 🐛

https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by AaronJan** [comment]
@CREEATION Thanks for the notice! I will make it happen soon. 👍

**Comment by AaronJan** [comment]
> I took the first steps to migrating to 8.0: #15

Nice work!

I'm just started this task too... 😄  I'll take a look at your PR later today.

Cheers.

**Comment by Juice10** [comment]
> I'm just started this task too... 😄 I'll take a look at your PR later today.

Sweet! I just pushed a small tweak to it. Something I bumped into when requiring it in my own project. Just a heads up in case you took a look at it before I pushed the code.

**Comment by AaronJan** [comment]
> > I'm just started this task too... 😄 I'll take a look at your PR later today.
> 
> Sweet!
> 
> I just pushed a small tweak to it. Something I bumped into when requiring it in my own project. Just a heads up in case you took a look at it before I pushed the code.

Merged. 😄 

I'll continue working on this v8 migration and some e2e tests, thank you!

If you have any thoughts / suggestions, please let me know!

**Comment by AaronJan** [comment]
Migrated to the new `AtRule()` API (new version `v3.0.0-alpha.2` published, code is in `master` branch), seems faster. 😄 

I'll keep working on tests.
